file:
  # load_dir: "../dataset/cap_raw/*/*/" # traindata
  # load_dir: "../dataset/cap_raw/*/0/" # traindata
  # load_dir: "../dataset/athlete/"
  load_dir: "../dataset/November/*/*/"
  # load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # traindata
data:
  input_data: ["tactile"]
  output_data: ["tactile"]
  train_test_val_ratio: [9,1] # Train/Test/Valid ratio
  devide_csv: True
  skip_timestep: 1
  extend_timestep: 0
  stdev_tactile: 0.003
  stdev_joint: 0.02
  stdev_torque: 0.02
positional_encoding: #not used for lstm
  input_data: [] # list
  dimention: 10
scaling:
  # tactile_scale: "sqrt" # None, sqrt, log
  tactile_scale:  # None, sqrt, log
  mode: "normalization"
  normalization_range: [0.1, 0.9]
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "ae"
  structure: "BasicAE"
  # structure: "PatchFingerAE" # PatchFingerAE / BasicAE / CCAE
  activation: "sigmoid" # tanh, sigmoid
  epoch: 2000
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  torque_loss: 1.0
  label_loss: 1.0
  finger_loss: [1.0,1.0,1.0,3.0,1.0]
  input_dim: 
  # hid_dim: 100
  hid_dim: 50
  # batch_size: 30
  batch_size: 20
test:
  save_weight_dir: "./output/ae/2023-11-15/"
  load_dir: "../dataset/athlete/"
  # load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # for test
  # load_dir: "../dataset/eval/" # for test
  # model_filename: "ae_1809.pth" #sqrt
  # model_filename: "ae_1938.pth" #normal
  model_filename: "ae_1995.pth" #log