file:
  # load_dir: "../dataset/cap_raw/*/*/" # traindata
  # load_dir: "../dataset/cap_raw/*/0/" # traindata
  load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # traindata
data:
  input_data: ["joint", "tactile", "Coordinates_Tactile",]
  output_data: ["desjoint", "tactile"]
  train_test_val_ratio: [8,2] # Train/Test/Valid ratio
  devide_csv: True
  skip_timestep: 20 # training frequency = 100 / skip_timestep
  extend_timestep: 10
positional_encoding: #not used for lstm
  input_data: [] # list
  dimention: 10
scaling:
  mode: "normalization"
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "lstm"
  activation: "tanh" # tanh, sigmoid
  # epoch: 100
  epoch: 1000
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  input_dim: 
  # rec_dim: 50
  rec_dim: 100
  output_dim: 
  # batch_size: 30
  batch_size: 8
  seq_num: 1
  model_ae_name: "ae"
  ae:
    model_filepath: "./output/ae/2023-10-30/weight/ae_991.pth"
    scaling_df_path: "./output/ae/2023-10-30/scaling_params.csv"
    hid_dim: 100
    activation: "tanh"
test:
  save_weight_dir: "./output/ae_lstm/2023-10-30/"
  # load_dir: "../dataset/cap_raw/*/0/" # for test
  load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # traindata
  # load_dir: "../dataset/eval/" # for test
  # load_dir: "../dataset/cap_raw/science/*/" # for test
  scaling_df_path: "./output/ae_lstm/2023-10-30/scaling_params.csv"
  model_filepath: "./output/ae_lstm/2023-10-30/weight/lstm_991.pth"