file:
  # load_dir: "../dataset/cap_raw/*/*/" # traindata
  # load_dir: "../dataset/cap_raw/*/0/" # traindata
  # load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # traindata
  # load_dir: "../dataset/athlete/"
  # load_dir: "../dataset/November/*/*/"
  load_dir: "/media/handlingteam/ubuntu/ah_record_data/slide/*/"

  # load_dir: "../dataset/November/science/0/20231121_144742_h1_science_0_1_edit"
data:
  # input_data: ["joint", "tactile", "torque", "Coordinates_Tactile",]
  input_data: ["joint", "tactile", "torque"]
  # input_data: ["joint", "tactile"]
  output_data: ["desjoint", "tactile", "torque", "label"] # if you use label, write here
  # output_data: ["desjoint", "tactile"]
  train_test_val_ratio: [10,0] # Train/Test/Valid ratio
  devide_csv: True
  skip_timestep: 20 # training frequency = 100 / skip_timestep
  extend_timestep: 50 # extend the end of the last timestep data
  stdev_tactile: 0 # add random noise to input of model
  stdev_joint: 0.02
  stdev_torque: 0.02
positional_encoding: #not used for lstm
  input_data: [] # list
  dimention: 10
scaling:
  # tactile_scale: "sqrt" # None, sqrt, log
  tactile_scale: 
  mode: "normalization"
  normalization_range: [0.1, 0.9]
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "lstm"
  activation: "sigmoid" # tanh, sigmoid
  loss_constraint: 1.0 # float or None
  # epoch: 100
  epoch: 10000
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  torque_loss: 1.0
  label_loss: 1.0
  finger_loss: [1.0,1.0,1.0,1.0,1.0]
  input_dim: 
  # rec_dim: 50
  rec_dim: 100
  output_dim: 
  # batch_size: 30
  batch_size: 60
  seq_num: 1
  model_ae_name: "ae"
  ae:
    ae_config_dir: "./output/ae/2023-11-23/" # None, filepath
    # model_filepath: "./output/ae/2023-10-30/weight/ae_991.pth"
    model_filename: "ae_1999.pth"
    # scaling_df_path: "./output/ae/2023-10-30/scaling_params.csv"
    # hid_dim: 100
    # activation: "tanh"
test:
  save_weight_dir: "./output/ae_lstm/2023-11-25_constraint/"
  # load_dir: "../dataset/athlete/"
  load_dir: "../dataset/November/*/*/"
  # load_dir: "../dataset/November/science/0/20231121_144742_h1_science_0_1"
  # load_dir: "../dataset/November/tea/90_far/"
  # load_dir: "../dataset/cap_raw/athlete/0/" # for test
  # load_dir: ["../dataset/cap_raw/*/0/", "../dataset/cap_raw/*/90/"] # traindata
  # load_dir: "../dataset/eval/" # for test
  # load_dir: "../dataset/cap_raw/science/*/" # for test
  # scaling_df_path: "./output/ae_lstm/2023-10-30/scaling_params.csv"
  model_filename: "lstm_9991.pth"