file:
  # load_dir: "../dataset/cap_raw/*/*/" # traindata
  load_dir: "../dataset/cap_raw/*/0/" # traindata
data:
  input_data: ["tactile"]
  outputType: ["Tactile"]
  train_test_val_ratio: [8,2] # Train/Test/Valid ratio
  devide_csv: True
positional_encoding: #not used for lstm
  input_data: [] # list
  dimention: 10
scaling:
  mode: "normalization"
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "ccae"
  activation: "tanh" # tanh, sigmoid
  # epoch: 100
  epoch: 1000
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  input_dim: 
  # rec_dim: 50
  hid_dim: 100
  output_dim: 
  # batch_size: 30
  batch_size: 6
  seq_num: 20
test:
  # load_dir: "../dataset/cap_raw/*/0/" # for test
  load_dir: "../dataset/eval/" # for test
  # load_dir: "../dataset/cap_raw/science/*/" # for test
  scaling_df_path: "./output/ae/scaling_params.csv"
  model_filepath: "./output/ae/weight/ae_921.pth"