file:
  # loadDirs: "_Coordinates_JOINTTACTILELabel_tacC/*/success/" # traindata
  load_dir: "../dataset/cap_raw/*/*/" # traindata
  savelog_filepath: "" # Loss, Training condition (yaml name), 
data:
  input_data: ["joint", "tactile", "Coordinates_Tactile"]
  outputType: ["Tactile"]
  additionalInputType: ["CoG_Tactile", "CoG_Tactile_pe"] # Center of Gravity (CoG), CoG processed by positional encoding(CoG_pe)
  train_test_val_ratio: [7,3,0] # Train/Test/Valid ratio
  devide_csv: True
  num_patch: 22 # total num of sensor patches
  num_data: 1152 # total num of input tactile data
positional_encoding:
  input_data: [] # list
  dimention: 10
scaling:
  mode: "normalization"
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "lstm"
  epoch: 100
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  input_dim: 
  rec_dim: 50
  output_dim: 
  batch_size: 10000
test:
  model_filepath: "./weight/lstm/lstm_99.pth"