file:
  load_dir: "../dataset/cap_raw/*/*/" # traindata
data:
  input_data: ["joint", "tactile", "Coordinates_Tactile"]
  outputType: ["Tactile"]
  train_test_val_ratio: [7,3] # Train/Test/Valid ratio
  devide_csv: True
positional_encoding: #not used for lstm
  input_data: [] # list
  dimention: 10
scaling:
  mode: "normalization"
  range: "patch"
  separate_axis: True
  separate_joint: True
model:
  model_name: "lstm"
  activation: "sigmoid" # tanh
  epoch: 100
  optimizer: "adam"
  learning_rate: 0.001
  tactile_loss: 1.0
  joint_loss: 1.0
  input_dim: 
  rec_dim: 50
  output_dim: 
  batch_size: 13
  seq_num: 10
test:
  model_filepath: "./weight/lstm/lstm_99.pth"